### ISSUE TITLE
Send alerts after the end_time, flatline rule issue 

### ISSUE THREAD

**Issue by vivek-rajshekar** [0xSeb/elastalert_hour_range#6]
We would like the alert to get sent at the end of the cycle but looks like we cannot control the time when alerts will be sent ?
start_time: "4:00"
end_time: "20:00"

Can we get an advice on this issue please ? Thanks

**Comment by vivek-rajshekar** [comment]
@0xSeb - Would this be a bug or we are missing any parameter to be configured to send alerts at end_time, please advice ?

**Comment by 0xSeb** [comment]
This is not a feature as far as I know, alerts are sent when they are triggered. I do not maintain this repo as I don't work with this anymore but feel free to add a PR if you find a way to do this :)
